spawn-interval-seconds: 10

enabled-mobs:
  ZOMBIE: 3
  SKELETON: 2
  CREEPER: 1

enabled-bloodmoon-mobs: {}

enabled-mythicmobs:

spawn-radius:
  min: 20
  max: 80

mobs-per-player: 3
 
max-spawn-per-player: 10  